### ISSUE TITLE
coupyraight infrindgrament (REAL)

### ISSUE THREAD

**Issue by m0uka** [H7KZ/AdventOfCode2022inJS#1]
hello mr. H7KZ,

it has come to my attention that you have made an unauthorized use of my copyrighted work entitled "advent of code 2022, day 2, by m0uka" (the "Work").   

 as you neither asked for nor received permission to use the Work nor to make or distribute copies, including electronic copies, of same, i believe you have willfully infringed my rights under 17 U.S.C. Section 101 et seq. and could be liable for statutory damages as high as $150,000 as set forth in Section 504(c)(2) therein.

i demand that you immediately cease the use and distribution of all infringing works derived from the Work, and all copies, including electronic copies, of same, that you deliver to me, if applicable, all unused, undistributed copies of same, or destroy such copies immediately !!!

delet fast!! or my lawyer will sue you
with all regards,  

m0uka, CEO, m0uka corporation

**Comment by H7KZ** [comment]
Hello mr. m0uka,

I'd like to inform you that I didn't use your copyrighted work entitled "advent of code 2022, day 2, by m0uka". I did in fact take an insipiration from a website called stackoverflow, exactly this post: https://www.reddit.com/r/adventofcode/comments/zac2v2/2022_day_2_solutions By the terms set by stackoverflow I am allowed to take insipration by the following term ShareAlike https://creativecommons.org/licenses/by-sa/4.0/

I wish you a good evening
Best regards,
H7KZ

**Comment by m0uka** [comment]
you linked reddit, but are talking about stackoverflow???? EXPOSED!! YOU ARE GOING TO JAIL FOR A LONG TIME MISTER

**Comment by H7KZ** [comment]
oh, my mistake sorry. Still. Fuck you.
